
<div id="app">
  <el-container style="height: 1000px; border: 1px solid #eee">
    <el-aside width="150px" style="background-color: rgb(238, 241, 246)">
      <el-menu>
        <el-submenu index="1">
          <template slot="title"><i class="el-icon-message"></i>图片</template>
          <el-menu-item-group>
            <el-menu-item index="1-1" @click="addElement(1)" @click="openBackgroud">背景图</el-menu-item>
            <el-menu-item index="1-2" @click="addElement(2)" @click="openImage">图片</el-menu-item>
          </el-menu-item-group>
        </el-submenu>
        <el-submenu index="2">
          <template slot="title"><i class="el-icon-menu"></i>视频</template>
          <el-menu-item-group>
            <el-menu-item index="2-1" @click="addElement(3)" @click="openVideo">视频</el-menu-item>
          </el-menu-item-group>
        </el-submenu>
        <el-submenu index="3">
          <template slot="title"><i class="el-icon-setting"></i>文本</template>
          <el-menu-item-group>
            <el-menu-item index="3-1" @click="addElement(4)" @click="openText">文本</el-menu-item>
          </el-menu-item-group>
        </el-submenu>
        <el-submenu index="3">
          <template slot="title"><i class="el-icon-setting"></i>时间</template>
          <el-menu-item-group>
            <el-menu-item index="3-1" @click="addElement(5)" @click="openTime">倒计时</el-menu-item>
          </el-menu-item-group>
        </el-submenu>
        <el-menu-item index="4">
          <i class="el-icon-setting"></i>
          <span slot="title">保存</span>
        </el-menu-item>
      </el-menu>
    </el-aside>
    
    <el-container>
      <el-main>
        <div class="draw-main">
          <div class="list" id="list" :isDraggable="true">
              <vue-drag-resize v-for="(rect, index) in elements"
                              :key="index" 
                              :w="rect.width"
                              :h="rect.height"
                              :x="rect.left"
                              :y="rect.top"
                              :parentW="listWidth"
                              :parentH="listHeight"
                              :axis="rect.axis"
                              :isActive="rect.active"
                              :minw="rect.minw"
                              :minh="rect.minh"
                              :isDraggable="rect.draggable"
                              :isResizable="rect.resizable"
                              :parentLimitation="true"
                              :snapToGrid="rect.snapToGrid"
                              :aspectRatio="rect.aspectRatio"
                              :z="rect.zIndex"
                              :contentClass="rect.class"
                              v-on:activated="activateEv(index)"
                              v-on:deactivated="deactivateEv(index)"
                              v-on:dragging="changePosition($event, index)"
                              v-on:resizing="changeSize($event, index)"
                              :type="rect.type"
                              :imageUrl="rect.imageUrl"
                              :headline="rect.headline"
              >
                  <div class="filler" :style="{backgroundColor:rect.color}">
                    <el-button class="float-button-bottom" type="primary" icon="el-icon-bottom" size="mini" @click="toBottom(index)" round></el-button>
                    <el-button class="float-button-top" type="primary" icon="el-icon-top" size="mini" @click="toTop(index)" round></el-button>
                    <el-button class="float-button-edit" type="primary" icon="el-icon-edit" size="mini" @click="editElement(index)" round></el-button>
                    <el-button class="float-button-remove" type="primary" icon="el-icon-delete" @click="removeElement(index)" size="mini" round></el-button>
                    <template v-if="rect.type === '1'">
                      <img :src="rect.imageUrl" alt="" width="100%" height="100%">
                    </template>
                    <template v-else-if="rect.type === '2'">
                      <a><img :src="rect.imageUrl" alt="" width="100%" height="100%"></a>
                    </template>
                    <template v-else-if="rect.type === '3'">
                      <p>{{rect.headline}}</p>
                    </template>
                    <template v-else>
                      <p>{{rect.headline}}</p>
                    </template>
                  </div>
              </vue-drag-resize>
          </div>
        </div>
      </el-main>
    </el-container>
  </el-container>
  <div class="tab-container">
    <el-dialog :visible.sync="dialogFormVisible">
      <el-form
        :model="questionForm"
        ref="dataForm"
        label-position="left"
        label-width="90px"
        style="width: 400px; margin-left:50px;"
      >
        <el-form-item label="宽度">
          <el-input v-model="questionForm.width" />
        </el-form-item>
        <el-form-item label="高度">
          <el-input v-model="questionForm.height" />
        </el-form-item>
        <template v-if="questionForm.type === '1'">
          <el-upload
            action="<?= $block->getImageUploadUrl() ?>"
            :data="{'form_key':'<?php echo $block->getFormKey() ?>'}"
            list-type="picture-card"
            :auto-upload="true"
            :on-success="uploadSuccess" 
            :on-remove="removeSuccess"
            :before-upload="beforeUpload"   
            :class="{ hideUpload: !showUpload }" >
            <i class="el-icon-plus"></i>
          </el-upload>
          <el-dialog :visible.sync="dialogVisible">
            <img width="100%" :src="dialogImageUrl" alt="">
          </el-dialog>
        </template>
        <template v-else-if="questionForm.type === '2'">
          <el-upload
              action="<?= $block->getImageUploadUrl() ?>"
              :data="{'form_key':'<?php echo $block->getFormKey() ?>'}"
              list-type="picture-card"
              :auto-upload="true"
              :on-success="uploadSuccess" 
              :on-remove="removeSuccess"
              :before-upload="beforeUpload"   
              :class="{ hideUpload: !showUpload }" >
              <i class="el-icon-plus"></i>
          </el-upload>
          <el-dialog :visible.sync="dialogVisible">
            <img width="100%" :src="dialogImageUrl" alt="">
          </el-dialog>
        </template>
        <template v-else-if="questionForm.type === '3'">
          <el-form-item label="文本">
            <el-input v-model="questionForm.headline" />
          </el-form-item>
        </template>
        <template v-else-if="questionForm.type === '4'">
          <el-form-item label="文本">
            <el-input v-model="questionForm.headline" />
          </el-form-item>
        </template>
        <template v-else>
          <el-form-item label="文本">
            <el-input v-model="questionForm.headline" />
          </el-form-item>
        </template>
        
      </el-form>
      <div slot="footer" class="dialog-footer">
        <el-button @click="dialogFormVisible = false">取消</el-button>
        <el-button type="primary" @click=" createData() ">确定</el-button>
      </div>
    </el-dialog>
  </div>
</div>
<script>
new Vue({
  el: '#app',
  data: function() {
    return {
       visible: false,
       isCollapse: true,
       listWidth: 200,
       listHeight: 200,
       elements:<?= json_encode($block->renderElements()) ?>,
        input: "",
        questionForm: {
          width: "",
          height: "",
          imageUrl:"",
        },
        dialogFormVisible: false,
        dialogImageUrl: '',
        dialogVisible: false,
        showUpload: true,
    }
  },
  mounted() {
      let listEl = document.getElementById('list');
      this.listWidth = listEl.clientWidth;
      this.listHeight = listEl.clientHeight;
      window.addEventListener('resize', ()=>{
          this.listWidth = listEl.clientWidth;
          this.listHeight = listEl.clientHeight;
      })
  },

  computed: {
      rects() {
          //return this.$store.state.rect.rects
      }
  },

  methods: {
      activateEv(index) {
          //this.$store.dispatch('rect/setActive', {id: index});
      },

      deactivateEv(index) {
          //this.$store.dispatch('rect/unsetActive', {id: index});
      },

      changePosition(newRect, index) {

          // this.$store.dispatch('rect/setTop', {id: index, top: newRect.top});
          // this.$store.dispatch('rect/setLeft', {id: index, left: newRect.left});
          // this.$store.dispatch('rect/setWidth', {id: index, width: newRect.width});
          // this.$store.dispatch('rect/setHeight', {id: index, height: newRect.height});
      },

      changeSize(newRect, index) {
          // this.$store.dispatch('rect/setTop', {id: index, top: newRect.top});
          // this.$store.dispatch('rect/setLeft', {id: index, left: newRect.left});
          // this.$store.dispatch('rect/setWidth', {id: index, width: newRect.width});
          // this.$store.dispatch('rect/setHeight', {id: index, height: newRect.height});
      },
      handleOpen(key, keyPath) {
        //console.log(key, keyPath);
      },
      handleClose(key, keyPath) {
        //console.log(key, keyPath);
      },
      removeElement(index){
        this.elements.splice(index, 1);
        //elements.splice(elements.indexOf(element), 1);
      },
      addElement(type) {
        switch(type){
            case 1:
              this.questionForm = {
                type:"1",
                width: "",
                height: "",
              };
              break
            case 2:
              this.questionForm = {
                type:"2",
                width: "",
                height: "",
              };
                break
            case 3:
              this.questionForm = {
                type:"3",
                width: "",
                height: "",
              };
              break
            case 4:
              this.questionForm = {
                type:"4",
                width: "",
                height: "",
                headline:""
              };
              break
            default:
                //这里是没有找到对应的值处理
              break
        }
        
        this.dialogFormVisible = true;
      },
      editElement(index) {
        console.log(this.elements[index].width);
        switch(this.elements[index].type){
            case 1:
              this.questionForm = {
                index:this.elements[index].index,
                type:this.elements[index].type,
                width: this.elements[index].width,
                height: this.elements[index].height,
              };
              break
            case 2:
              this.questionForm = {
                index:this.elements[index].index,
                type:this.elements[index].type,
                width: this.elements[index].width,
                height: this.elements[index].height,
              };
                break
            case 3:
              this.questionForm = {
                index:this.elements[index].index,
                type:this.elements[index].type,
                width: this.elements[index].width,
                height: this.elements[index].height,
              };
              break
            case 4:
              this.questionForm = {
                index:this.elements[index].index,
                type:this.elements[index].type,
                width: this.elements[index].width,
                height: this.elements[index].height,
                headline:this.elements[index].headline,
              };
              break
            default:
                //这里是没有找到对应的值处理
              break
        }
        
        this.dialogFormVisible = true;
      },
      //添加增加题目
      createData() {
        const params = this.questionForm;
        params.width = parseInt(params.width); 
        params.height = parseInt(params.height);
        params.index = parseInt(params.index);  
        if(params.index)
        {
          switch(params.type){
              case '1':
                this.elements[index].width = params.width;
                this.elements[index].height = params.height;
                this.elements[index].imageUrl = this.imageUrl;
                break;
              case '2':
                this.elements[index].width = params.width;
                this.elements[index].height = params.height;
                this.elements[index].imageUrl = this.imageUrl;
                break;
              case '3':
                this.elements[index].width = params.width;
                this.elements[index].height = params.height;
                this.elements[index].headline = params.headline;
                break;
              case '4':
                this.elements[index].width = params.width;
                this.elements[index].height = params.height;
                this.elements[index].headline = params.headline;
                break;
              default:
                break;
          }
          Vue.set(this.elements, index, this.elements[index]);
        }else{
          switch(params.type){
              case '1':
                this.elements.push({
                    width: params.width,
                    height: params.height,
                    left: 10,
                    top: 10,
                    isActive: true,
                    imageUrl:this.imageUrl,
                    type:params.type,
                    zIndex:1,
                });
                break;
              case '2':
                this.elements.push({
                    width: params.width,
                    height: params.height,
                    left: 10,
                    top: 10,
                    isActive: true,
                    imageUrl:this.imageUrl,
                    type:params.type,
                    zIndex:1,
                });
                break;
              case '3':
                this.elements.push({
                    width: params.width,
                    height: params.height,
                    left: 10,
                    top: 10,
                    isActive: true,
                    type:params.type,
                    zIndex:1,
                });
                break;
              case '4':
                this.elements.push({
                    width: params.width,
                    height: params.height,
                    left: 10,
                    top: 10,
                    isActive: true,
                    headline:params.headline,
                    type:params.type,
                    zIndex:1,
                });
                break;
              default:
                break;
          }
        }
        
        this.dialogFormVisible = false;

        //如果需要调用接口，请打开注释
      //   const res = await saveSubject(params);
      //   console.log(res);
      //   if (res.code === "0000") {
      //     this.$message({
      //       type: "info",
      //       message: "保存成功",
      //     });
      //     this.dialogFormVisible = false;
      //     this.getQuerySubjectList();
      //     return;
      //   }
      //   this.$message({
      //     type: "error",
      //     message: "保存失败",
      //   });
      },
      toggleUpload() {
        this.showUpload = !this.showUpload
      },
      uploadSuccess(response, file, fileList) {
         console.log(response);
         this.imageUrl = response;
      },
      beforeUpload(file) {
          // 这里我也准备只接受jpg的格式储存所以我就直接用了官方提供的代码
          const isJPG = file.type === 'image/jpeg';
          const isLt2M = file.size / 1024 / 1024 < 2;
          
          if (!isJPG) {
              this.$message.error('上传图片只能是 JPG 格式!');
          }
          if (!isLt2M) {
              this.$message.error('上传图片大小不能超过 2MB!');
          }
          return isJPG && isLt2M;
      },
      handleRemove(file, fileList) {
        console.log(file, fileList);
      },
      handlePictureCardPreview(file) {
        this.dialogImageUrl = file.url;
        this.dialogVisible = true;
      },
      toBottom(index){
        this.elements[index].zIndex = this.elements[index].zIndex-1;
        Vue.set(this.elements, index, this.elements[index]);
      },
      toTop(index){
        this.elements[index].zIndex = this.elements[index].zIndex+1;
        Vue.set(this.elements, index, this.elements[index]);
      }
    }
})
</script>