<?php
/** @var \Silk\CmsTool\Block\Adminhtml\Edit\Block\Draw $block */

$vueComponents = $block->getVueComponents();

?>

<div id="cmstool-block">
    <cmstool-block :config="config" :element="element">
    </cmstool-block>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "blockElement": {
                "vueComponents": <?= json_encode($vueComponents) ?>,
                "data": {
                    "element"  : <?= json_encode($block->renderElement()) ?>,
                    "config": {
                        "imageUploadUrl"   : "<?= $block->getImageUploadUrl() ?>",
                        "imageDeleteUrl"   : "<?= $block->getImageDeleteUrl() ?>",
                        "imageUploadFileId": "<?= $block->getImageUploadFileId() ?>",
                        "lazyMinItemsCount": "1000",
                        "translation": {
                            "block"          : "<?= __('Block') ?>",
                            "click"          : "<?= __('Click') ?>",
                            "createFirstNode": "<?= __('to create your first node.') ?>",
                            "createSubNode"  : "<?= __('to create sub node or drag and drop other nodes here.') ?>",
                            "append"         : "<?= __('Append') ?>",
                            "edit"           : "<?= __('Edit') ?>",
                            "delete"         : "<?= __('Delete') ?>",
                            "addNode"        : "<?= __('New node') ?>",
                            "addImage"        : "<?= __('New Image') ?>",
                            "addText"        : "<?= __('New Text') ?>",
                            "addVideo"        : "<?= __('New Video') ?>",
                            "nodeType"       : "<?= __('Node Type') ?>",
                            "nodeName"       : "<?= __('Node name') ?>",
                            "nodeClasses"    : "<?= __('Node CSS classes') ?>",
                            "selectNodeType" : "<?= __('Select Node Type') ?>",
                            "pleaseSelect"   : "<?= __('Please select a') ?>",
                            "targetLabel"    : "<?= __('Node target blank') ?>",
                            "category"       : "<?= __('Category') ?>",
                            "categoryChild"  : "<?= __('Parent Category') ?>",
                            "categoryId"     : "<?= __('Category ID') ?>",
                            "block"          : "<?= __('Block') ?>",
                            "blockId"        : "<?= __('Block ID') ?>",
                            "page"           : "<?= __('Page') ?>",
                            "pageId"         : "<?= __('Page URL key') ?>",
                            "customURL"      : "<?= __('Custom URL') ?>",
                            "product"        : "<?= __('Product') ?>",
                            "productId"      : "<?= __('Product ID') ?>",
                            "imageAltText"   : "<?= __('Image Alt text') ?>",
                            "selectedItemId" : "<?= __('Selected Item Id') ?>"
                        }
                    }
                }
            }
        }
    }
</script>
