<?php
/** @var \Silk\CmsTool\Block\Adminhtml\Edit\Block\Draw $block */

$vueComponents = $block->getVueComponents();

?>
<div id="cmstool-block">
    <cmstool-block :config="config" :elements="elements">
    </cmstool-block>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "blockElement": {
                "vueComponents": <?= json_encode($vueComponents) ?>,
                "data": {
                    "elements"  : <?= json_encode($block->renderElement()) ?>,
                    "config": {
                        "translation": {
                            "categoryId"     : "<?= __('Category ID') ?>"
                        }
                    }
                }
            }
        }
    }
</script>


<script>
    require(
        [
            'jquery',
            // 'Magento_Ui/js/modal/modal',
            'popupWindow'
        ],
        function($, modal) {
            // var options = {
            //     type: 'popup',
            //     responsive: true,
            //     innerScroll: true,
            //     title: 'Create Block',
            //     buttons: [{
            //         text: $.mage.__('Close'),
            //         class: 'modal-close',
            //         click: function (){
            //             this.closeModal();
            //         }
            //     },{
            //         text: $.mage.__('Create'),
            //         class: 'modal-add',
            //         click: function (){
            //             console.log($('#width').val());
            //             console.log($('#height').val());
            //             $("#add-block").click();
            //             this.closeModal();
            //         }
            //     }]
            // };
            // modal(options, $('#modal-content'));
            // $("#draw").on('click',function(){
            //     $("#modal-content").modal("openModal");
            // });
            $("#draw").popupWindow({
                "windowURL": "<?= $block->getDrawUrl() ?>",
                "windowName": "Draw Block",
                "width": 1960,
                "height": 840,
                "centerScreen": true,
                "left": 0,
                "top": 0,
                "resizable": 1,
                "scrollbars": 1,
                "menubar": 1,
                "toolbar":1
            });
        }
    );
</script>